State Tracing
paritytech/substrate-archive pull request #92
Opened 2020-09-02 12:19 UTC by insipx

2020-10-21 10:58 UTC, dvdplm requested changes
Left some nitpicks. I have a hard time seeing where this is heading and I could use a better description; it seems like this PR doesn't doesn't store the traces anywhere?
I am also a little concerned about having to fork polkadot for this – what do we need from upstream to reach a stable point? After all our end goal here is to provide a production quality state tracing tool so it's critical that we have a good maintenance story and a stable situation upstream. Can you elaborate a bit on what the plan is?

2020-10-21 10:58 UTC, dvdplm commented on Cargo.toml
> +sp-database = { git = "https://github.com/paritytech/substrate", package="sp-database" , rev = "35fe3cd1bc4b64cadb0bc6196ae40173db65bb28" }
rev `35fe3cd1bc4b64cadb0bc6196ae40173db65bb28` is rather old (Aug 26) – what is stopping us from using `master` or `2.0`, i.e. what motivated the change?

2020-10-21 10:58 UTC, dvdplm commented on bin/polkadot-archive/src/archive.rs
> +    ksm_rt::native_version,
funny whitespace

2020-10-21 10:58 UTC, dvdplm commented on src/actors.rs
> +                        }
Maybe we can do something like

```
Ok(v) if v == 0 => { … … },
Ok(_) => {} // but maybe we want to log something here?
Err(FailedLoadingJob) => { … … }
```

Not sure if it's better, but sometimes explicit is good.

2020-10-21 10:58 UTC, dvdplm commented on src/actors/workers/state_tracing.rs
> +const TRACE_TARGETS: &str = "assets,atomic-swap,aura,authority-discovery,authorship, \
How do we obtain this list? Can we do anything smart here? Can we stick them in a toml file at least? Ideally we should have an RPC to ask the node about the supported targets.

2020-10-21 10:58 UTC, dvdplm commented on src/actors/workers/state_tracing.rs
> +        }
funny whitespace and spurious `println`?

2020-10-21 10:58 UTC, dvdplm commented on src/actors/workers/state_tracing.rs
> +        tracing::subscriber::set_global_default(sub).unwrap();
Use `expect`

2020-10-21 10:58 UTC, dvdplm commented on src/backend/frontend.rs
> +        block_construction: ExecutionStrategy::NativeWhenPossible,
dumb q: how is `NativeWhenPossible` different from `NativeElseWasm`?

2020-11-18 21:14 UTC, insipx commented
Closing in favor of #134

2020-11-18 21:14 UTC, closed without merging